- name: Set Nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Set Nginx Enabled site
  template:
    src: enabled-site.j2
    dest: /etc/nginx/sites/enabled/hello_world_website

- name: Set Nginx html site
  template:
    src: hello_world_website.html.j2
    dest: /var/www/testsite/index.html