- name: Get all backends
  debug:
    msg: "{{ item }}"
  loop: "{{ query('inventory_hostnames', 'haproxy_backends') }}"

- name: Set HAProxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg